default_language_version:
    python: python3.9

repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args: ["--skip-string-normalization", "--line-length=140"]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]
        exclude: ^doc
        verbose: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-json
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: pretty-format-json
        args: ["--autofix"]
      - id: sort-simple-yaml
      - id: trailing-whitespace
      - id: requirements-txt-fixer
